[build]
  functions = "netlify/functions"

[functions]
  external_node_modules = ["express", "express-handlebars", "markdown-it", "mongoose"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Serve static files directly (CSS, JS, images)
[[redirects]]
  from = "/css/*"
  to = "/css/:splat"
  status = 200

[[redirects]]
  from = "/js/*"
  to = "/js/:splat"
  status = 200

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
