[build]
  functions = "netlify/functions"
  publish = "public"

[functions]
  external_node_modules = ["express", "express-handlebars", "markdown-it", "mongoose", "marked", "highlight.js"]
  node_bundler = "esbuild"
  included_files = ["views/**", "content/**", "public/**"]

# Serve static files directly (CSS, JS, images) - these should come BEFORE the catch-all
[[redirects]]
  from = "/css/*"
  to = "/css/:splat"
  status = 200

[[redirects]]
  from = "/js/*"
  to = "/js/:splat"
  status = 200

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# Catch-all redirect to function (this must be LAST)
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
